package hive.hive.com.hive.Utils;

/**
 * Created by abhishekgupta on 21/02/16.
 */
public enum Enums {

    FACEBOOK("FACEBOOK"),

    //Activities
    MAINACTIVITY("MAINACTIVITY"),

    //Adapters
    HIVELISTADAPTER("HIVELISTADAPTER"),
    CUSTOMLISTADAPTER("CUSTOMLISTADAPTER"),
    ALLEVENTCUSTOMLISTADAPTER("ALLEVENTCUSTOMLISTADAPTER"),

    //Connections
    CLOSESTHIVELISTCONNECTION("CLOSESTHIVELISTCONNECTION"),
    GETGEOLOCATIONDETAILSCONNECTION("GETGEOLOCATIONDETAILSCONNECTION"),
    GETIMAGECONNECTION("GETIMAGECONNECTION"),
    GETUSERSETTINGSCONNECTION("GETUSERSETTINGSCONNECTION"),
    HIVEPOSTSCONNECTION("HIVEPOSTSCONNECTION"),
    LIKEPOSTCONNECTION("LIKEPOSTCONNECTION"),
    POSTTOHIVECONNECTION("POSTTOHIVECONNECTION"),
    REGISTERUSERCONNECTION("REGISTERUSERCONNECTION"),
    REGISTERUSERGEOTAGCONNECTION("REGISTERUSERGEOTAGCONNECTION"),
    USERFBDETAILS("USERFBDETAILS"),
    EVENTLISTCONNECTION("EVENTLISTCONNECTION"),
    EVENTINTERESTCONNECTION("EVENTINTERESTCONNECTION"),
    CREATEEVENTCONNECTION("CREATEEVENTCONNECTION"),

    //Fragments
    ALLPOSTSFRAGMENT("ALLPOSTSFRAGMENT"),
    USERPROFILEFRAGMENT("USERPROFILEFRAGMENT"),
    LOGINFRAGMENT("LOGINFRAGMENT"),
    CREATEPOSTFRAGMENT("CREATEPOSTFRAGMENT"),
    EDITPROFILEFRAGMENT("EDITPROFILEFRAGMENT"),
    EVENTSFRAGMENT("EVENTSFRAGMENT"),
    EVENTDETAILFRAGMENT("EVENTDETAILFRAGMENT"),
    REGISTRATIONFRAGMENT("REGISTRATIONFRAGMENT"),

    //GSONEntities
    CLOSESTHIVEDETAIL("CLOSESTHIVEDETAIL"),
    HIVEPOSTDETAILS("HIVEPOSTDETAILS"),
    EVENTLISTDETAILS("EVENTLISTDETAILS"),
    USERDETAILS("USERDETAILS"),
    USERSETTINGSDETAILS("USERSETTINGSDETAILS"),
    EVENTDETAILS("EVENTDETAILS"),

    //Utils
    FACEBOOKUTILS("FACEBOOKUTILS"),
    FILECACHE("FILECACHE"),
    CONNECTIONUTILS("CONNECTIONUTILS"),
    IMAGELOADER("IMAGELOADER"),
    INFINITESCROLLLISTENER("INFINITESCROLLLISTENER"),
    MEDIAUTILS("MEDIAUTILS"),
    MEMORYCACHE("MEMORYCACHE"),
    STRINGUTILS("STRINGUTILS"),
    CUSTOMLOCATIONMANAGER("CUSTOMLOCATIONMANAGER"),
    EMAILVALIDATOR("EMAILVALIDATOR"),
    LOCATIONUTILS("LOCATIONUTILS"),
    LOCATIONVALUE("LOCATIONVALUE"),
    LOGINUTILS("LOGINUTILS"),
    PASSWORDVALIDATOR("PASSWORDVALIDATOR"),
    USERSESSIONUTILS("USERSESSIONUTILS"),

    //LOGIN TYPE
    HIVE_LOGIN("1"),
    FACEBOOK_LOGIN("2"),

    //Dialogs
    CREATEEVENTDIALOG("CREATEEVENTDIALOG"),
    CREATEPOSTDIALOG("CREATEPOSTDIALOG"),
    SELECTIONDIALOG("SELECTIONDIALOG");

    private String enumVal;

    Enums(String enumVal) {
        this.enumVal = enumVal;
    }

    public String getVal() {
        return enumVal;
    }
}
